import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Banner, Navbar, SectionCards } from '../components'


/**Discover-videos-app - version 2.09  - index js - Features:
 * 
 *      --> Migrating 'Card' component to 'SectionCards'
 * 
 * Note: It is a pre test for image sizing
*/

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username='netseriesuser@gmail.com'/>
      <Banner 
        title='Clifford the red dog' 
        subtitle='a very cute dog' 
        imgUrl={'/statics/clifford.the.red.dog.png'}/>
       <SectionCards title='Disney' />
    </div>
  )
}
