import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Banner, Navbar, SectionCards } from '../components'
import { getPopularVideos, getVideos } from '../lib/videos';

/**Discover-videos-app - version 3.01 - index js - Features:
 * 
 *      --> Adding the class module 'main' ro add white space
 * 
 * Note: These are the first steps to control the query in a 
 * dynamic way
 * 
 * when these changes of query are made sometimes needs to refresh
 * the page
*/

export async function getServerSideProps() {

  const disneyVideos = await getVideos('marvel universe trailers');

  const travelVideos = await getVideos('travel');

  const productivityVideos = await getVideos('productivity');

  const popularVideos = await getPopularVideos();

  return {
    props: { disneyVideos, travelVideos, productivityVideos, popularVideos }, // will be passed to the page component as props
  };
}

export default function Home({ disneyVideos, travelVideos, productivityVideos, popularVideos }) {
  console.log({ disneyVideos });

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.main}>

        <Navbar username='netseriesuser@gmail.com'/>
        <Banner 
          title='Clifford the red dog' 
          subtitle='a very cute dog' 
          imgUrl={'/statics/clifford.the.red.dog.png'}/>
          <div className={styles.sectionWrapper}>
            <SectionCards title='Disney'  videos={disneyVideos} size='large'/>
            <SectionCards title='Travel'  videos={travelVideos} size='small'/>
            <SectionCards title='Productivity'  videos={productivityVideos} size='medium'/>
            <SectionCards title='Popular'  videos={popularVideos} size='small'/>
          </div>
      </div>
    </div>
  )
}
